In [1]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.naive_bayes import MultinomialNB

In [4]:
le=preprocessing.LabelEncoder()
clf = MultinomialNB()
data=pd.read_csv('data2.csv')

In [17]:
features=[feat for feat in data]
targetLabel=features[-1]
features.remove(features[-1])
features

['Outlook', 'Temperature', 'Humidity', 'Wind']

In [6]:
diff_values=[]
for f in features:
    for v in data[f]:
        if v not in diff_values:
            diff_values.append(v)

diff_values

['sunny',
 'overcast',
 'rain',
 'hot',
 'mild',
 'cool',
 'high',
 'normal',
 'weak',
 'strong']

In [7]:
dataArray=np.array(data.iloc[:,0:-1])
dataArray

array([['sunny', 'hot', 'high', 'weak'],
       ['sunny', 'hot', 'high', 'strong'],
       ['overcast', 'hot', 'high', 'weak'],
       ['rain', 'mild', 'high', 'weak'],
       ['rain', 'cool', 'normal', 'weak'],
       ['rain', 'cool', 'normal', 'strong'],
       ['overcast', 'cool', 'normal', 'strong'],
       ['sunny', 'mild', 'high', 'weak'],
       ['sunny', 'cool', 'normal', 'weak'],
       ['rain', 'mild', 'normal', 'weak'],
       ['sunny', 'mild', 'normal', 'strong'],
       ['overcast', 'mild', 'high', 'strong'],
       ['overcast', 'hot', 'normal', 'weak'],
       ['rain', 'mild', 'high', 'strong']], dtype=object)

In [8]:
le.fit(diff_values)
list(le.classes_)

['cool',
 'high',
 'hot',
 'mild',
 'normal',
 'overcast',
 'rain',
 'strong',
 'sunny',
 'weak']

In [9]:
trans=[]
for d in dataArray:
    trans.append(le.transform(d))
trans

[array([8, 2, 1, 9]),
 array([8, 2, 1, 7]),
 array([5, 2, 1, 9]),
 array([6, 3, 1, 9]),
 array([6, 0, 4, 9]),
 array([6, 0, 4, 7]),
 array([5, 0, 4, 7]),
 array([8, 3, 1, 9]),
 array([8, 0, 4, 9]),
 array([6, 3, 4, 9]),
 array([8, 3, 4, 7]),
 array([5, 3, 1, 7]),
 array([5, 2, 4, 9]),
 array([6, 3, 1, 7])]

In [18]:
target=data[targetLabel]
target

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
Name: Answer, dtype: object

In [19]:
target=np.array(target)
tar=[]
for t in target:
    if t == "yes":
        tar.append(1)
    else:
        tar.append(0)
tar

[0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0]

In [20]:
clf.fit(trans,tar)

MultinomialNB()

In [21]:
predicting=["sunny","cool","high","strong"]
pre_array=le.transform(predicting)

In [23]:
pre_array=np.reshape(pre_array,(1,4))
pre_array

array([[8, 0, 1, 7]])

In [24]:
print(clf.predict(pre_array))

[0]
